"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 06:56:32.217555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('fuente', sa.String(length=64), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('empresa', sa.String(length=300), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.String(length=300), nullable=True),
    sa.Column('modalidad', sa.String(length=50), nullable=True),
    sa.Column('salario', sa.String(length=200), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_ingesta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ofertas_empresa'), 'ofertas', ['empresa'], unique=False)
    op.create_index(op.f('ix_ofertas_external_id'), 'ofertas', ['external_id'], unique=True)
    op.create_index(op.f('ix_ofertas_fecha_ingesta'), 'ofertas', ['fecha_ingesta'], unique=False)
    op.create_index(op.f('ix_ofertas_fecha_publicacion'), 'ofertas', ['fecha_publicacion'], unique=False)
    op.create_index(op.f('ix_ofertas_fuente'), 'ofertas', ['fuente'], unique=False)
    op.create_index(op.f('ix_ofertas_modalidad'), 'ofertas', ['modalidad'], unique=False)
    op.create_index(op.f('ix_ofertas_ubicacion'), 'ofertas', ['ubicacion'], unique=False)
    op.create_table('perfiles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('busqueda', sa.JSON(), nullable=False),
    sa.Column('contacto', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('experiencia', sa.JSON(), nullable=False),
    sa.Column('educacion', sa.JSON(), nullable=False),
    sa.Column('idiomas', sa.JSON(), nullable=False),
    sa.Column('certificaciones', sa.JSON(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfiles_activo'), 'perfiles', ['activo'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.String(length=64), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('obligatorios_ok', sa.Integer(), nullable=False),
    sa.Column('obligatorios_total', sa.Integer(), nullable=False),
    sa.Column('deseables_ok', sa.Integer(), nullable=False),
    sa.Column('deseables_total', sa.Integer(), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=False),
    sa.Column('evaluado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oferta_id', 'perfil_id', name='uq_match_oferta_perfil')
    )
    op.create_index(op.f('ix_matches_nivel'), 'matches', ['nivel'], unique=False)
    op.create_index(op.f('ix_matches_oferta_id'), 'matches', ['oferta_id'], unique=False)
    op.create_index(op.f('ix_matches_perfil_id'), 'matches', ['perfil_id'], unique=False)
    op.create_table('ofertas_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oferta_id', 'skill', name='uq_oferta_skill')
    )
    op.create_index(op.f('ix_ofertas_skills_oferta_id'), 'ofertas_skills', ['oferta_id'], unique=False)
    op.create_index('ix_ofertas_skills_skill', 'ofertas_skills', ['skill'], unique=False)
    op.create_table('postulaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.String(length=64), nullable=False),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('fecha_postulacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oferta_id', 'perfil_id', name='uq_postulacion_oferta_perfil')
    )
    op.create_index(op.f('ix_postulaciones_estado'), 'postulaciones', ['estado'], unique=False)
    op.create_index(op.f('ix_postulaciones_oferta_id'), 'postulaciones', ['oferta_id'], unique=False)
    op.create_index(op.f('ix_postulaciones_perfil_id'), 'postulaciones', ['perfil_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postulaciones_perfil_id'), table_name='postulaciones')
    op.drop_index(op.f('ix_postulaciones_oferta_id'), table_name='postulaciones')
    op.drop_index(op.f('ix_postulaciones_estado'), table_name='postulaciones')
    op.drop_table('postulaciones')
    op.drop_index('ix_ofertas_skills_skill', table_name='ofertas_skills')
    op.drop_index(op.f('ix_ofertas_skills_oferta_id'), table_name='ofertas_skills')
    op.drop_table('ofertas_skills')
    op.drop_index(op.f('ix_matches_perfil_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_oferta_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_nivel'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_perfiles_activo'), table_name='perfiles')
    op.drop_table('perfiles')
    op.drop_index(op.f('ix_ofertas_ubicacion'), table_name='ofertas')
    op.drop_index(op.f('ix_ofertas_modalidad'), table_name='ofertas')
    op.drop_index(op.f('ix_ofertas_fuente'), table_name='ofertas')
    op.drop_index(op.f('ix_ofertas_fecha_publicacion'), table_name='ofertas')
    op.drop_index(op.f('ix_ofertas_fecha_ingesta'), table_name='ofertas')
    op.drop_index(op.f('ix_ofertas_external_id'), table_name='ofertas')
    op.drop_index(op.f('ix_ofertas_empresa'), table_name='ofertas')
    op.drop_table('ofertas')
    # ### end Alembic commands ###
